name: word_checker
description: A word checker app built with Flutter.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  another_flushbar: ^1.10.28
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  hive: ^2.1.0
  intl: ^0.17.0
  logger: ^1.1.0
  sliding_up_panel: ^2.0.0+1
  smooth_page_indicator: ^1.0.0+2
  stacked: ^2.3.3
  stacked_hooks: ^0.2.2
  stacked_services: ^0.8.18
  stacked_themes: ^0.3.8+1
  syncfusion_flutter_sliders: ^20.1.52

dependency_overrides:
  get: 4.6.1
  json_annotation: 4.3.0

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  stacked_generator: ^0.6.2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
