name: word_checker
description: A word checker app built with Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  animations: ^2.0.2
  another_flushbar: ^1.10.28
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.17.0
  logger: ^1.1.0
  stacked: ^2.3.3
  stacked_services:
    git:
      url: https://github.com/thecokerdavid/stacked.git
      path: packages/stacked_services/
      branch: master
  stacked_themes: ^0.3.8+1

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  stacked_generator: ^0.6.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
